name       : libimobiledevice
version    : 1.2.0
release    : 5
source     :
    - http://www.libimobiledevice.org/downloads/libimobiledevice-1.2.0.tar.bz2 : 786b0de0875053bf61b5531a86ae8119e320edab724fc62fe2150cc931f11037
license    : LGPL-2.1
summary    : A library to communicate with services of Apple iOS devices using native protocols.
description: |
    libimobiledevice is a cross-platform software library that talks the protocols to support iPhone, iPod Touch, iPad and Apple TV devices.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libusbmuxd)
    - pkgconfig(libplist)
    - pkgconfig(libtasn1)
    - libgcrypt-devel
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2016-5104.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
