name       : libimobiledevice
version    : 1.2.0
release    : 6
source     :
    - https://github.com/libimobiledevice/libimobiledevice/archive/1.2.0.tar.gz : 8ba1ea817691b3548b83371f8ec22d73d1e37f8fda7c899ac9c7121d924ca830
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library to communicate with services of Apple iOS devices using native protocols.
description: |
    libimobiledevice is a cross-platform software library that talks the protocols to support iPhone, iPod Touch, iPad and Apple TV devices.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libusbmuxd)
    - pkgconfig(libplist)
    - pkgconfig(libtasn1)
    - libgcrypt-devel
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2016-5104.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
